output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.mvp-eks.cluster_endpoint
}

output "cluster_oidc_issuer_url" {
  description = "kubectl config as generated by the module."
  value       = module.mvp-eks.cluster_oidc_issuer_url
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.mvp-eks.config_map_aws_auth
}

output "node_groups" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.mvp-eks.node_groups	
}
